background   #333333
foreground   #ffffff
cursor       #ffffff

font_size 9.5

tab_bar_style        separator
tab_separator        "  |  "
tab_bar_edge         top
active_tab_font_style   bold

map ctrl+t new_tab

clipboard_control write-clipboard write-primary read-clipboard read-primary

tab_title_template "{title:<15.15}"
active_tab_title_template "{title:<15.15}"
